# NOTE(ww): These settings were chosen to be compatible with `black`'s defaults,
# modulo the increase in `line_length`.
[tool.isort]
line_length = 100
known_first_party = [
  "mate",
  "mate_common",
  "mate_rest_client",
  "mate_cli",
  "mate_query",
  "dwarfcore",
  "dwarflang",
  "mantiserve"
]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 100
exclude = '''
(
  /(
    | \.git          # root of the project
    | \.mypy_cache
    | submodules
  )/
)
'''
