# Provides a minimal clean and correct build environment for Phase 2 challenges.
#
# This Dockerfile does NOT attempt to reproduce the runtime environment
# for actually running Phase 2 challenges.

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
  apt-get install -qq -y --fix-missing build-essential tzdata clang-10 \
    clang++-10 flex bison pmccabe gdb strace libstdc++-8-dev libwrap0-dev \
    libssl-dev libsasl2-dev groff groff-base libdb-dev net-tools openssh-server \
    openssh-client vim make wget netcat curl unzip zlib1g-dev bzip2 python3 \
    python3-dev python3-pip python2 libjemalloc-dev ldap-utils libsqlite3-dev \
    php libdlt2 libev4 libuv1 libwebsockets15 mosquitto automake autoconf \
    pkgconf libboost-all-dev cmake libpcre3-dev scons

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 700 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 700 && \
    update-alternatives --install /usr/bin/clang-cpp clang-cpp /usr/bin/clang-cpp-10 700

RUN pip3 install netifaces
