name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the mate-dev image
        run: ./ci/gha-docker-build "dev" "mate-dev"

      - name: Build the MATE bdist
        run: |
          docker run \
            --rm -v $(pwd):/mate \
            "ghcr.io/galoisinc/mate-dev:${GITHUB_SHA}" \
            ./shake.sh -j bdist

      - name: Build and push the mate-dist image
        run: |
          # HACK
          sudo chmod a+r -R .out/

          ./ci/gha-docker-build "dist" "mate-dist"
