name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: "1"
  # This will be empty on events that aren't pull requests.
  ACTUAL_GITHUB_SHA_ON_PULL_REQUEST: "${{ github.event.pull_request.head.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 3

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the mate-dev image
        run: ./ci/gha-docker-build "dev" "mate-dev"

      - name: Build the MATE bdist
        run: |
          docker run \
            --rm -v $(pwd):/mate \
            "ghcr.io/galoisinc/mate-dev:${GITHUB_RUN_ID}" \
            ./shake.sh -j bdist

      - name: Compress the MATE bdist
        run: |
          tar czf mate-bdist.tar.gz ./.out/bdist

      - name: Upload the MATE bdist
        uses: actions/upload-artifact@v3
        with:
          name: mate-bdist
          path: mate-bdist.tar.gz

      - name: Build and push the mate-dist image
        run: |
          # HACK: These files are owned by the container root, so we can't
          # read them until we change their permissions.
          sudo chmod a+r -R .out/

          ./ci/gha-docker-build "dist" "mate-dist"

  test-legacy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull mate-dev
        run: |
          docker pull "ghcr.io/galoisinc/mate-dev:${GITHUB_RUN_ID}"

      # - name: Fetch the MATE bdist
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: mate-bdist

      # - name: Extract the MATE bdist
      #   run: |
      #     tar xzf mate-dist.tar.gz

      - name: Run legacy tests
        run: |
          # TODO: Figure out the right way to plumb the integration test setting.
          docker run \
            -e MATE_INTEGRATION_TESTS=0 \
            --rm -v $(pwd):/mate \
            "ghcr.io/galoisinc/mate-dev:${GITHUB_RUN_ID}" \
              ./shake.sh --skip=build pytests -- -- -n logical -x
