name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the mate-dev image
        run: |
          docker pull "ghcr.io/galoisinc/mate-dev:main" || true
          docker pull "ghcr.io/galoisinc/mate-dev:3f669142c740617fe269deafb0b2ea61198d29db"

          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from "ghcr.io/galoisinc/mate-dev:main" \
            --cache-from "ghcr.io/galoisinc/mate-dev:3f669142c740617fe269deafb0b2ea61198d29db" \
            --target dev \
            --tag "ghcr.io/galoisinc/mate-dev:${GITHUB_SHA}" \
            .

          docker push \
            "ghcr.io/galoisinc/mate-dev:${GITHUB_SHA}"

          # If we're on main or we were manually dispatched,
          # then we additionally tag at mate-dev:main.
          if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            docker tag \
              "ghcr.io/galoisinc/mate-dev:${GITHUB_SHA}" \
              "ghcr.io/galoisinc/mate-dev:main"

            docker push "ghcr.io/galoisinc/mate-dev:main"
          fi

      - name: Build the MATE bdist
        run: |
          docker run \
            --rm -v $(pwd):/mate \
            "ghcr.io/galoisinc/mate-dev:${GITHUB_SHA}" \
            ./shake.sh -j bdist

      - name: Build and push the mate-dist image
        run: |
          docker pull "ghcr.io/galoisinc/mate-dist:main" || true
          docker pull "ghcr.io/galoisinc/mate-dist:3f669142c740617fe269deafb0b2ea61198d29db"

          # HACK
          sudo chmod a+r -R .out/

          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from "ghcr.io/galoisinc/mate-dist:main" \
            --cache-from "ghcr.io/galoisinc/mate-dist:3f669142c740617fe269deafb0b2ea61198d29db" \
            --target dist \
            --tag "ghcr.io/galoisinc/mate-dist:${GITHUB_SHA}" \
            .

          docker push \
            "ghcr.io/galoisinc/mate-dist:${GITHUB_SHA}"

          # If we're on main or we were manually dispatched,
          # then we additionally tag at mate-dist:main.
          if [[ "${GITHUB_REF_NAME}" == "main" || "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            docker tag \
              "ghcr.io/galoisinc/mate-dist:${GITHUB_SHA}" \
              "ghcr.io/galoisinc/mate-dist:main"

            docker push "ghcr.io/galoisinc/mate-dist:main"
          fi
