name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: mate-dev
        run: |
          docker build --target dev -t mate-dev .

      - name: bdist
        run: |
          docker run --rm -v $(pwd):/mate mate-dev:latest ./shake.sh -j bdist

      - name: mate-dist
        run: |
          # HACK
          sudo chmod a+r -R .out/
          docker build --target dist -t mate-dist .
