name: Tests

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  fetch-bdist:
    runs-on: ubuntu-latest
    steps:
      - name: Download the MATE bdist
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "mate-bdist"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/bdist.zip`, Buffer.from(download.data));

      - name: Extract the MATE bdist
        run: |
          unzip bdist.zip
          rm bdist.zip
          ls .out/bdist

  # legacy:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Fetch
  #       run: |
  #         true
