name: Tests

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  legacy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull mate-dist
        run: |
          docker pull "ghcr.io/galoisinc/mate-dist:${GITHUB_SHA}"
